= Dokumentation des Projektes:

== M1 Projektverständnis
Die von mir angelegten .adoc Dateien waren für mich nicht schwer zu bearbeiten,
da ich durch das Unimodell Softwareengeeniering schon Vorerfahrung habe. Des weiteren
findet man auch viele gute Informationen und Grundlagen im Internet.
Eine größere Herausforderung war es die Spickzettel Datei zubearbeiten.
Hierfür musste ich mich durch die Grundlagen von Flutter durcharbeiten, was eine längere
Zeit in anspruch genommen hat. Jedoch erklären die Flutter entwickler auf ihrer Seite alles
sehr gut und ich konnte mich mehr und mehr mit Flutter vertraut machen.


== M2 - Projektstart
Der start in das Projekt viel mir mittelmäßig schwer. Ich finde das sich der Syntax von flutter/dart
von den mir bekannten Programmiersprachen unterscheidet. Weswegen es mir anfangs schwer viel einen
Überblick zu erhalten. Allerdings wenn man sich durcharbeitet, findet man immer mehr und mehr
Anschluss und erkennt sich wiederholende Muster.
Daher kam ich schnell in die Design arbeit rein und konnte das Grundlayout gut erstellen.


== M3 - Erste Inhalte
Mit den ersten Inhalten, des Projektes die vorallem Design teschniche implemntierungen hatten. Legte
ich mein Fokus vorallem drauf die verschiedenen Container zu designen und zu gestalten. Zur Vereinfachung  
legte ich mir erstmal nur Beispielwerte, die als Platzhalter dienen und meinen Fokus auf das Design zu legen.
Anfangs war das Designen der Implementierungen ungewohnt, es unterscheidet sich schon von dem mir gewohnten css.
Allerdings merkte ich schon das es mit flutter etwas moderner ist und nach einpaar Zeilen code merkte ich, das 
sich einiges wiederholt und konnte mich gut an die neue Syntax gewöhnen.
Das dartellen der Diagramme fiel mir überraschender Weise einfacher als Gedacht, ich habe auf youtube ein sehr 
praktisches Tutorial gefunden, das mir sehr gut geholfen hat. 
