= Usersrorys

Mit diesem Dokument möchte ich User Stories aus Nutzersicht festlegen.
Sie dienen dazu, Anforderungen aus Nutzersicht zu formulieren und daraus Taks abzuleiten.

== M3 - Erste Inhalte (Home Seite)
* Als Nutzer möchte ich eine simple Beispiel-Übersicht erhalten, damit ich sehen kann, wie meine
Kosten und Verbräuche später dargestellt werden.

* Als Verbraucher möchte ich sehen, wie viel Zeit mir noch bis zum Ende eines Beispiel-Turnus
bleibt, damit ich ein besseres Zeitgefühl für meine Turnusablesung bekomme.

* Als Nutzer möchte ich meinen Monatsdurchschnitt mit einem Beispielwert sehen,
damit ich die ich geplante Darstellung erkennen knn.

* Als Nutzer möchte ich ein Beispiel-Diagramm mit Verbrauchswerte sehen,
damit ich eine visuelle Einschätzung meiner Verbäuche erhalte.

== M4 - Eingabe Seite
* Als Nutzer möchte ich eine detallierte Seite auf der ich alle relevanten Daten, für meine Abrechnung sehen und verwalten kann.

* Als Nutzer möchte ich meine Turnusdaten eingeben, damit darausfolgeende Berechnungen korrekt ausgeführt werden können.

* Als Nutzer möchte ich meine Vertragsdaten erfassen, damit die App meine Kosten richtig ableiten kann.

* Als Nutzer möchte ich meine Zählerstände eingeben und verwalten können. Damit mein Verbrauch dokumentiert und korrekt berechnet werden kann. 